pipeline:
  stages:
    - stage:
        variables:
          - name: SNYK_IMAGE
            type: String
            value: snyk/snyk-cli:1.745.0-maven-3.5.4
        type: CI
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.eksCluster
              namespace: harness-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  spec:
                    connectorRef: org.Dockerhub
                    image: snyk/snyk-cli:1.745.0-maven-3.5.4
                    shell: Sh
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk test --json-file-output=/shared/customer_artifacts/snyk_output.json || true
                    privileged: true
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1.0"
                  name: Snyk Test
                  identifier: Snyk_Test
                  failureStrategies: []
              - step:
                  type: Security
                  name: Snyk STO
                  identifier: Snyk_STO
                  spec:
                    privileged: true
                    settings:
                      policy_type: ingestionOnly
                      scan_type: repository
                      product_name: snyk
                      product_config_name: default
                      manual_upload_filename: snyk_output.json
                      customer_artifacts_path: /shared/customer_artifacts
                      repository_project: springbootemployee-api
                      repository_branch: master
          cloneCodebase: true
          sharedPaths:
            - /shared/customer_artifacts
        name: CI
        identifier: CI
  properties:
    ci:
      codebase:
        repoName: springbootemployee-api
        connectorRef: org.Github
        build: <+input>
  projectIdentifier: Snyk
  orgIdentifier: default
  name: Snyk Test
  identifier: Snyk_Test
  description: Test local project for vulnerabilities.
