pipeline:
  stages:
    - stage:
        variables:
          - name: SNYK_IMAGE
            type: String
            value: snyk/snyk-cli:1.745.0-maven-3.5.4
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  spec:
                    connectorRef: org.Dockerhub
                    image: <+CI.variables.SNYK_IMAGE>
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk iac test ./employee-K8s.yaml || true
                    privileged: true
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                  name: Snyk IaC
                  identifier: Snyk_IaC
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        name: CI
        identifier: CI
  properties:
    ci:
      codebase:
        repoName: springbootemployee-api
        connectorRef: org.Github
        build: <+input>
  projectIdentifier: Snyk
  orgIdentifier: default
  name: Snyk IaC
  identifier: Snyk_IaC
  description: Find  security  issues in your Infrastructure as Code files. See snyk iac --help for full instructions.
