pipeline:
  stages:
    - stage:
        variables:
          - name: SNYK_IMAGE
            type: String
            value: snyk/snyk-cli:1.745.0-maven-3.5.4
        type: CI
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.GKE
              namespace: harness-builds
          execution:
            steps:
              - step:
                  type: Run
                  spec:
                    connectorRef: org.Dockerhub
                    image: snyk/snyk-cli:1.745.0-maven-3.5.4
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk test
                    privileged: true
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1.0"
                  name: Snyk Test
                  identifier: Snyk_Test
          cloneCodebase: true
          sharedPaths:
            - /shared/customer_artifacts
        name: CI
        identifier: CI
  properties:
    ci:
      codebase:
        repoName: springbootemployee-api
        connectorRef: org.Github
        build: <+input>
  projectIdentifier: Snyk
  orgIdentifier: default
  name: Snyk Test
  identifier: Snyk_Test
  description: Test local project for vulnerabilities.
