pipeline:
  stages:
    - stage:
        variables:
          - value: snyk/snyk-cli:1.745.0-maven-3.5.4
            type: String
            name: SNYK_IMAGE
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  spec:
                    privileged: true
                    image: <+CI.variables.SNYK_IMAGE>
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>N")>
                    connectorRef: org.Dockerhub
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk code test || true
                  name: Snyk Code
                  identifier: Snyk_Code
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        name: CI
        identifier: CI
  properties:
    ci:
      codebase:
        repoName: springbootemployee-api
        connectorRef: org.Github
        build: <+input>
  projectIdentifier: Snyk
  orgIdentifier: default
  name: Snyk Code
  identifier: Snyk_Code
  description: Find security issues using static code analysis. See snyk  code --help for full instructions.
