pipeline:
    tags: {}
    stages:
        - stage:
              variables:
                  - name: SNYK_IMAGE
                    type: String
                    value: snyk/snyk-cli:1.745.0-maven-3.5.4
                  - name: MAVEN_IMAGE
                    type: String
                    value: maven:3.8.3-openjdk-11-slim
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-builds
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Run
                                      name: Snyk Test
                                      identifier: Snyk_Test
                                      spec:
                                          connectorRef: org.Dockerhub
                                          image: <+CI.variables.SNYK_IMAGE>
                                          command: |-
                                              snyk config set api=$SNYK_TOKEN
                                              snyk test || true
                                          privileged: true
                                          envVariables:
                                              SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                                - step:
                                      type: Run
                                      name: Snyk Code Test
                                      identifier: Snyk_Code_Test
                                      spec:
                                          connectorRef: org.Dockerhub
                                          image: <+CI.variables.SNYK_IMAGE>
                                          command: |-
                                              snyk config set api=$SNYK_TOKEN
                                              snyk code test || true
                                          privileged: true
                                          envVariables:
                                              SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                          - step:
                                type: Run
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+CI.variables.MAVEN_IMAGE>
                                    command: mvn -DskipTests -Dsnyk.skip package
                                    privileged: true
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>N")>
                                name: Compile
                                identifier: Compile
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build Container
                                identifier: Build_Container
                                spec:
                                    connectorRef: org.Dockerhub
                                    repo: mansong/springbootemployee
                                    tags:
                                        - <+pipeline.sequenceId>
                                    dockerfile: Dockerfile.harness
                                    optimize: true
                          - step:
                                type: Run
                                name: Snyk Container Test
                                identifier: Snyk_Container_Test
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+CI.variables.SNYK_IMAGE>
                                    command: |-
                                        snyk config set api=$SNYK_TOKEN
                                        snyk test mansong/springbootemployee:<+pipeline.sequenceid> || true
                                    privileged: true
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                  cloneCodebase: true
                  serviceConfig:
                      serviceRef: ""
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
              name: CI
              identifier: CI
        - stage:
              name: Deploy Staging
              identifier: Deploy_Staging
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: employeeapi
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: org.Dockerhub
                                          imagePath: mansong/springbootemployee
                                          tag: <+pipeline.stages.CI.spec.execution.steps.Build_Container.spec.tags>
                              manifests:
                                  - manifest:
                                        identifier: staging_manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/api/templates/employee.yaml
                                                    repoName: springbootemployee
                                                    branch: master
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: staging_values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/api/values.yaml
                                                    repoName: springbootemployee
                                                    branch: master
                  infrastructure:
                      environmentRef: staging
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKE
                              namespace: staging
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: Snyk IaC Test
                                identifier: Snyk_IaC_Test
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                SNYK_TOKEN=<+secrets.getValue("org.SNYK_TOKEN")>
                                                snyk config set api=$SNYK_TOKEN
                                                snyk iac test <+pipeline.stages.Deploy_Staging.spec.serviceConfig.serviceDefinition.spec.manifests.staging_manifest.spec.store.spec.paths> || true
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    properties:
        ci:
            codebase:
                repoName: springbootemployee-api
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Snyk
    orgIdentifier: default
    name: SpringBoot Employee API
    identifier: SpringBoot_Employee_API
    description: Find security issues using static code analysis. See snyk  code --help for full instructions.
