apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-employee-api-argocd
spec:
  selector:
    matchLabels:
      app: springboot-employee-api-argocd
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-employee-api-argocd
    spec:
      containers:
        - name: springboot-employee-api-argocd
          image: pasapples/springbootemployee:multi-stage-add-layers
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
